services:

  maria:
    container_name: dbadmin-maria
    image: mariadb:10-ubi
    volumes:
      - ../tools/mysql/disable-ssl.cnf:/etc/my.cnf.d/disable-ssl.cnf
    restart: always
    expose:
      - 3306
    environment:
      MARIADB_ROOT_PASSWORD: dbadmin
    networks:
      dbserver-dev-net:
        aliases:
          - maria.db.dbadmin.loc

  mysql:
    container_name: dbadmin-mysql
    image: mysql:8.0
    volumes:
      - ../tools/mysql/disable-ssl.cnf:/etc/my.cnf.d/disable-ssl.cnf
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: dbadmin
    networks:
      dbserver-dev-net:
        aliases:
          - mysql.db.dbadmin.loc

  pgsql-14:
    container_name: dbadmin-pgsql-14
    image: postgres:14.15-alpine3.21
    restart: always
    expose:
      - 5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: dbadmin
    networks:
      dbserver-dev-net:
        aliases:
          - pgsql-14.db.dbadmin.loc

  pgsql-17:
    container_name: dbadmin-pgsql-17
    image: postgres:17-alpine3.21
    restart: always
    expose:
      - 5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: dbadmin
    networks:
      dbserver-dev-net:
        aliases:
          - pgsql-17.db.dbadmin.loc

networks:
  dbserver-dev-net:
    driver: bridge
    name: dbserver-dev-net
