services:

  dbadmin-demo:
    container_name: dbadmin-demo
    build:
      context: ./
      dockerfile: demo/Dockerfile
      args:
        - PHP_USER=dbadmin
        - PHP_UID=${PHP_UID:-1000}
        - PHP_GID=${PHP_GID:-1000}
    volumes:
      - ../..:/var/www
      - ../sqlite:/var/lib/sqlite
    ports:
      - 7090:8080
    extra_hosts:
      - "pgsql.addr=host-gateway"
      - "maria.addr=host-gateway"
      - "mysql.addr=host-gateway"
      - "infisical.local=host-gateway"
