services:

  dbadmin-dev:
    build:
      target: dbadmin-dev-secrets
      additional_contexts:
        # Give access to the SSL certs dir.
        secrets-ssl: ../ssl
    volumes:
      - ../tools/aws:/home/dbadmin/.aws:ro
      - ../tools/gcp:/home/dbadmin/.gcp:ro
    environment:
      - AWS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    networks:
      - secrets-ssl-net

  dbadmin-cli:
    build:
      target: dbadmin-cli-secrets
      additional_contexts:
        # Give access to the SSL certs dir.
        secrets-ssl: ../ssl
    volumes:
      - ../tools/aws:/home/dbadmin/.aws
      - ../tools/gcp:/home/dbadmin/.config/gcloud
      - ../scripts/secrets:/home/dbadmin/secrets
    environment:
      - AWS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    networks:
      - secrets-ssl-net

networks:
  secrets-ssl-net:
    external: true
