services:

  dbadmin-demo:
    container_name: dbadmin-demo
    build:
      context: ./
      dockerfile: demo/Dockerfile
      args:
        - PHP_USER=dbadmin
        - PHP_UID=${PHP_UID:-1000}
        - PHP_GID=${PHP_GID:-1000}
    volumes:
      - ../..:/var/www
      - ../sqlite:/var/lib/sqlite
    ports:
      - 7090:8080
    extra_hosts:
      - "pgsql.addr=host-gateway"
      - "maria.addr=host-gateway"
      - "mysql.addr=host-gateway"
      - "infisical.local=host-gateway"

  dbadmin-dev:
    container_name: dbadmin-dev
    build:
      context: ./
      dockerfile: dev/Dockerfile
      args:
        - PHP_USER=dbadmin
        - PHP_UID=${PHP_UID:-1000}
        - PHP_GID=${PHP_GID:-1000}
    volumes:
      - ../../../dbadmin-app:/var/www
      - ../exports:/home/dbadmin/exports
      - ./config/.env.dbadmin:/var/www/.env.dbadmin
      - ./config/dbadmin.json:/var/www/config/dbadmin.json
      - ./config/dbadmin.php:/var/www/config/dbadmin.php
      - ./config/jaxon.php:/var/www/config/jaxon.php
      - ../sqlite:/var/lib/sqlite
      - ../sqlite/3/database.sqlite:/var/www/database/database.sqlite:rw
    ports:
      - 7091:8080
    extra_hosts:
      - "pgsql.addr=host-gateway"
      - "maria.addr=host-gateway"
      - "mysql.addr=host-gateway"
      - "infisical.local=host-gateway"

  dbadmin-app:
    container_name: dbadmin-app
    image: lagdo/jaxon-dbadmin:latest
    restart: always
    volumes:
      - ../exports:/home/dbadmin/exports
      - ./config/.env.dbadmin:/var/www/.env.dbadmin
      - ./config/dbadmin.json:/var/www/config/dbadmin.json
      - ./config/dbadmin.php:/var/www/config/dbadmin.php
      - ./config/jaxon.php:/var/www/config/jaxon.php
      - ../sqlite:/var/lib/sqlite
      - ../sqlite/3/database.sqlite:/var/www/database/database.sqlite:rw
    ports:
      - 7092:8080
    extra_hosts:
      - "pgsql.addr=host-gateway"
      - "maria.addr=host-gateway"
      - "mysql.addr=host-gateway"
      - "infisical.local=host-gateway"
