services:

  dbadmin-mariadb:
    container_name: dbadmin-mariadb
    image: mariadb:10-ubi
    volumes:
      - ./config/mysql/disable-ssl.cnf:/etc/my.cnf.d/disable-ssl.cnf
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dbadmin
    networks:
      - dbadmin-dev-net

  dbadmin-mysql:
    container_name: dbadmin-mysql
    image: mysql:8.0
    volumes:
      - ./config/mysql/disable-ssl.cnf:/etc/my.cnf.d/disable-ssl.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbadmin
    networks:
      - dbadmin-dev-net

  dbadmin-pgsql-14:
    container_name: dbadmin-pgsql-14
    image: postgres:14.15-alpine3.21
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: dbadmin
    networks:
      - dbadmin-dev-net

  dbadmin-pgsql-17:
    container_name: dbadmin-pgsql-17
    image: postgres:17-alpine3.21
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: dbadmin
    networks:
      - dbadmin-dev-net

networks:
  dbadmin-dev-net:
    driver: bridge
