server {
    listen 443 ssl;
    server_name  inf.secrets.loc;

    ssl_certificate     /etc/nginx/ssl/secrets.loc.crt;
    ssl_certificate_key /etc/nginx/ssl/secrets.loc.key;

    access_log  /var/log/nginx/inf.secrets.access.log main;
    error_log   /var/log/nginx/inf.secrets.error.log debug;

    location / {
        proxy_pass http://inf.secrets:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    server_name  aws.secrets.loc;

    ssl_certificate     /etc/nginx/ssl/secrets.loc.crt;
    ssl_certificate_key /etc/nginx/ssl/secrets.loc.key;

    access_log  /var/log/nginx/aws.secrets.access.log main;
    error_log   /var/log/nginx/aws.secrets.error.log debug;

    location / {
        proxy_pass http://aws.secrets:4566;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    server_name  gcp.secrets.loc;

    ssl_certificate     /etc/nginx/ssl/secrets.loc.crt;
    ssl_certificate_key /etc/nginx/ssl/secrets.loc.key;

    access_log  /var/log/nginx/gcp.secrets.access.log main;
    error_log   /var/log/nginx/gcp.secrets.error.log debug;

    location / {
        proxy_pass http://gcp.secrets:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 443 ssl;
    server_name  bao.secrets.loc;

    ssl_certificate     /etc/nginx/ssl/secrets.loc.crt;
    ssl_certificate_key /etc/nginx/ssl/secrets.loc.key;

    access_log  /var/log/nginx/bao.secrets.access.log main;
    error_log   /var/log/nginx/bao.secrets.error.log debug;

    location / {
        proxy_pass http://bao.secrets:8200;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
